name: Build and Deploy Hugo

on:
  push:
    branches:
      - main  # or whichever branch you develop on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: true  # set to true if your theme is a submodule

      # 2. Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # or pin to a specific version if you want

      # 3. Build the site
      - name: Build
        run: hugo --minify

      # 4. Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: nitishpatkar.com
